"""reports added

Revision ID: a3a0565784a4
Revises: d9e11032af98
Create Date: 2026-02-01 13:53:55.874655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a0565784a4'
down_revision: Union[str, Sequence[str], None] = 'd9e11032af98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
