"""notifications

Revision ID: b187de030186
Revises: 8d2a8c2578d0
Create Date: 2026-01-16 15:35:24.209185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b187de030186'
down_revision: Union[str, Sequence[str], None] = '8d2a8c2578d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('dedupe_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'notifications', ['dedupe_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_column('notifications', 'dedupe_key')
    # ### end Alembic commands ###
