"""stock_movement update

Revision ID: 057388980990
Revises: e0090af70069
Create Date: 2026-01-06 21:33:47.580465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057388980990'
down_revision: Union[str, Sequence[str], None] = 'e0090af70069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stock_movements_dedupe_key_key'), 'stock_movements', type_='unique')
    op.drop_column('stock_movements', 'sent_at')
    op.drop_column('stock_movements', 'dedupe_key')
    op.drop_column('stock_movements', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stock_movements', sa.Column('dedupe_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('stock_movements_dedupe_key_key'), 'stock_movements', ['dedupe_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
