"""updated user

Revision ID: aa1c8599f158
Revises: ef5e0277b753
Create Date: 2025-12-19 12:24:58.931844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1c8599f158'
down_revision: Union[str, Sequence[str], None] = 'ef5e0277b753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_movements', 'notes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'notes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
