"""stock_movement update

Revision ID: e0090af70069
Revises: 887ad7bc8851
Create Date: 2026-01-06 21:27:01.835187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0090af70069'
down_revision: Union[str, Sequence[str], None] = '887ad7bc8851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('dedupe_key', sa.String(), nullable=True))
    op.add_column('stock_movements', sa.Column('status', sa.String(), nullable=False))
    op.add_column('stock_movements', sa.Column('sent_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'stock_movements', ['dedupe_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='unique')
    op.drop_column('stock_movements', 'sent_at')
    op.drop_column('stock_movements', 'status')
    op.drop_column('stock_movements', 'dedupe_key')
    # ### end Alembic commands ###
